[package]
name = "examples-ping-pong-libc"
version = "0.10.0"
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
edition = "2021"

[dependencies]
examples-ping-pong-shared = { path = "../shared", version = "0.10" }
flmodules = { path = "../../../flmodules", version = "0.10" }
flarch = { path = "../../../flarch", features = ["node"], version = "0.10" }

console_error_panic_hook = "0.1.6"
log = "0.4"
wasm-logger = "0.2"
tokio = { version = "1", features = ["time"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
wee_alloc = "0.4.5"
ybc = "0.4"
yew = "0.20"
